name: API CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Docker build
        uses: docker/setup-buildx-action@v3
      - name: Build test container
        run: docker compose -f docker-compose.test.yml build
      - name: Start test container
        run: docker compose -f docker-compose.test.yml up -d db
      - name: Wait for DB
        run: |
          until docker compose -f docker-compose.test.yml exec db pg_isready -U test_user; do
            echo "Waiting for Postgres..."
            sleep 2
          done
      - name: Run Tests
        env:
          NOTES_DB_DSN: "postgres://test_user:test_password@localhost:5432/test_db?sslmode=disable"
        run: |
          cd backend
          go test ./... -v
      - name: Teardown
        if: always()
        run: docker compose -f docker-compose.test.yml down --volumes --remove-orphans
