name: API CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker api env for tests
        uses: ./.github/actions/docker-test-api-setup
      - name: Run Tests
        env:
          NOTES_DB_DSN: "postgres://test_user:test_password@localhost:5432/test_db?sslmode=disable"
        run: |
          cd backend
          go test ./... -v
      - name: Teardown
        if: always()
        run: docker compose -f docker-compose.test.yml down --volumes --remove-orphans
