name: Deploy

on:
  push:
    branches:
      - main
      - prod

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  api_checks:
    uses: ./.github/workflows/api.yml

  frontend_checks:
    uses: ./.github/workflows/frontend.yml

  codeql_checks:
    uses: ./.github/workflows/codeql.yml

  lint_and_validate:
    needs: [api_checks, frontend_checks, codeql_checks]
    uses: ./.github/workflows/lint-and-validate-terraform.yml
    name: Lint & Validate Terraform
    secrets:
      DOCKER_HUB_USER: ${{vars.DOCKER_HUB_USER}}
      DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}

  build_and_push_images:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: [api_checks, frontend_checks, codeql_checks, lint_and_validate]
    outputs:
      api_image_tag: ${{ steps.api_image.outputs.tag }}
      frontend_image_tag: ${{ steps.frontend_image.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build API Docker Image
        id: api_image
        env:
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.eu-west-1.amazonaws.com
          API_IMAGE_TAG=${{ github.sha }}
          API_IMAGE_URI="${{ vars.ECR_REPO_API}}:$API_IMAGE_TAG"
          docker build --compress -t $API_IMAGE_URI ./backend
          echo "tag=$API_IMAGE_URI" >> $GITHUB_OUTPUT
      - name: Scan API Docker Image with Trivy
        id: trivy_api
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ steps.api_image.outputs.tag }}
          format: "sarif"
          output: "trivy-api-results.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
      - name: Upload API Trivy Results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        continue-on-error: true
        if: always()
        with:
          sarif_file: "trivy-api-results.sarif"
          category: "trivy-api"
      - name: Fail if vulnerabilities found in API container
        if: steps.trivy_api.outcome == 'failure'
        run: |
          echo "Trivy found vulnerabilities in API image"
          exit 1
      - name: Push API Docker Image to ECR
        if: steps.trivy_api.outcome == 'success'
        env:
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.eu-west-1.amazonaws.com
          docker push ${{ steps.api_image.outputs.tag }}
      - name: Build Frontend Docker Image
        id: frontend_image
        if: steps.trivy_api.outcome == 'success'
        env:
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.eu-west-1.amazonaws.com
          FRONTEND_IMAGE_TAG=${{ github.sha }}
          FRONTEND_IMAGE_URI="${{ vars.ECR_REPO_FRONTEND}}:$FRONTEND_IMAGE_TAG"

          if [[ "$GITHUB_REF" == "refs/heads/prod" ]]; then
            API_URL="https://code.${{ vars.DOMAIN_NAME }}/v1"
          else
            API_URL="https://code.staging.${{ vars.DOMAIN_NAME }}/v1"
          fi

          docker build --compress \
            --build-arg VITE_API_BASE_URL="$API_URL" \
            -t $FRONTEND_IMAGE_URI ./frontend

          echo "tag=$FRONTEND_IMAGE_URI" >> $GITHUB_OUTPUT
      - name: Scan Frontend Docker Image with Trivy
        id: trivy_frontend
        if: steps.trivy_api.outcome == 'success'
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ steps.frontend_image.outputs.tag }}
          format: "sarif"
          output: "trivy-frontend-results.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
      - name: Upload Frontend Trivy Results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        continue-on-error: true
        if: always() && steps.trivy_api.outcome == 'success'
        with:
          sarif_file: "trivy-frontend-results.sarif"
          category: "trivy-frontend"
      - name: Fail if vulnerabilities found in Frontend container
        if: steps.trivy_api.outcome == 'success' && steps.trivy_frontend.outcome == 'failure'
        run: |
          echo "Trivy found vulnerabilities in Frontend image"
          exit 1
      - name: Push Frontend Docker Image to ECR
        if: steps.trivy_api.outcome == 'success' && steps.trivy_frontend.outcome == 'success'
        env:
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.eu-west-1.amazonaws.com
          docker push ${{ steps.frontend_image.outputs.tag }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build_and_push_images]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set variables
        run: |
          if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
              echo "prod" > .workspace
          else
              echo "staging" > .workspace
          fi
      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          export TF_VAR_ecr_api_image="${{ needs.build_and_push_images.outputs.api_image_tag }}"
          export TF_VAR_ecr_frontend_image="${{ needs.build_and_push_images.outputs.frontend_image_tag }}"
          export TF_VAR_ecr_prometheus_image="${{ vars.ECR_REPO_PROMETHEUS }}:latest"
          export TF_VAR_ecr_grafana_image="${{ vars.ECR_REPO_GRAFANA }}:latest"
          export TF_VAR_database_password=${{secrets.DATABASE_PASSWORD}}
          export TF_VAR_grafana_admin_password=${{secrets.GRAFANA_ADMIN_PASSWORD}}
          workspace=$(cat .workspace)
          cd infra/
          docker compose run --rm terraform -chdir=deploy/ init
          docker compose run --rm terraform -chdir=deploy/ workspace select -or-create $workspace
          docker compose run --rm terraform -chdir=deploy/ apply -auto-approve
