name: Teardown
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to teardown
        options:
          - staging
          - prod

jobs:
  teardown:
    name: Teardown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Terraform Teardown
        env:
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          export TF_WORKSPACE=${{ github.event.inputs.environment }}
          cd infra/
          docker compose run --rm terraform -chdir=deploy/ init
          docker compose run --rm terraform -chdir=deploy/ destroy -auto-approve
